spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finzy_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

jwt:
  secret: finzy-secret-key-please-change-this-in-production-2024
  expiration: 86400000

cloudinary:
  cloud-name: dtifs8jeb
  api-key: 211697358775511
  api-secret: Eho5KArrt5VjhGudFNxoQrDQCkk